name: Build Kernel

on:
  push:
    paths:
      - 'linux/**'
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu ARM64
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          debhelper \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          pahole

    - name: Building Kernel
      run: |
        cd linux
        date "+%Y%m%d%H%M%S" > .version
        make mvebu_defconfig
        make olddefconfig
        make --jobs=$(nproc) bindeb-pkg
        cd ..
        mkdir output
        mv *.deb ./output/

    - uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: ./output/*.deb
